#include "Constant.h"

/*    CURRENT UNITS      */
const UINT8 SCREEN_WIDTH = 80;
const UINT8 MSB = 0x80;
const UINT8 REMAINDER_MAX = 7;
const UINT8 BITS_PER = 8;
const UINT8 SHIFT = 3;
const UINT8 LINE_BODY = 0xFF;


/*     OTHER  UNITS      */
const UINT8 SCREEN_WIDTH_PIX = 640;
const UINT8 SCREEN_HEIGHT_PIX = 400;
const UINT8 VBORDER_BITS = 20;
const UINT8 HBORDER_BITS = 80;
const UINT8 SCREEN_WIDTH_WORD = 40;
const UINT8 SCREEN_WIDTH_LONG = 20;
const UINT8 SHIFT_WORD = 4;
const UINT8 LINE_BODY_WORD = 0xFFFF;
