tst_rast: tst_rast.o raster.o rast_asm.o Objects.o Model.o Renderer.o 
	cc68x -g tst_rast.o raster.o Objects.o Model.o Renderer.o -o tst_rast.tos

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

Objects.o: Objects.c Objects.h
	cc68x -g -c Objects.c
    
Model.o: Model.c Model.h
	cc68x -g -c Model.c
    
Renderer.o: Renderer.c Renderer.h
	cc68x -g -c Renderer.c
    
clean:
	$(RM) *.o
    
all: clean tst_rast
    
test: all
	$(tst_rast.tos)