game: raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Tron.o Constant.o mSetScrn.o Menu.o isr.o isr_asm.o globals.o PSG.o effects.o
	cc68x -g raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Tron.o Constant.o mSetScrn.o Menu.o isr.o isr_asm.o globals.o PSG.o effects.o -o Tron

tst_rast: tst_rast.o raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Constant.o
	cc68x -g tst_rast.o raster.o Objects.o Model.o Renderer.o Events.o Constant.o -o tst

tst_sound: TST_PSG.o PSG.o effects.o globals.o isr.o isr_asm.o Events.o Model.o Objects.o Constant.o
	cc68x -g TST_PSG.o PSG.o effects.o globals.o isr.o isr_asm.o Events.o Model.o Objects.o Constant.o -o psg

tst_key: isr.o isr_asm.o Events.o Objects.o Constant.o traplab.o globals.o PSG.o effects.o
	cc68x -g isr.o isr_asm.o Events.o Objects.o Constant.o traplab.o globals.o PSG.o effects.o -o t

traplab.o:
	cc68x -g -c traplab.c
    
effects.o: effects.c effects.h
	cc68x -g -c effects.c	

PSG.o: PSG.c PSG.h globals.h
	cc68x -g -c PSG.c

globals.o: globals.c globals.h
	cc68x -g -c globals.c
    
TST_PSG.o: TST_PSG.c PSG.h globals.h
	cc68x -g -c TST_PSG.c
	
Tron.o: Tron.c Tron.h    
	cc68x -g -c Tron.c
    
tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

Events.o: Events.c Events.h
	cc68x -g -c Events.c

Constant.o: Constant.c Constant.h
	cc68x -g -c Constant.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

Objects.o: Objects.c Objects.h
	cc68x -g -c Objects.c

Model.o: Model.c Model.h
	cc68x -g -c Model.c

Renderer.o: Renderer.c Renderer.h
	cc68x -g -c Renderer.c
    
mSetScrn.o: mSetScrn.s
	gen -D -L2 mSetScrn.s
    
Menu.o:Menu.c Menu.h    
	cc68x -g -c Menu.c
    
isr_asm.o:  isr_asm.s
	gen -D -L2 isr_asm.s
	
isr.o: isr.c isr.h
	cc68x -g -c isr.c
	    
clean:
	$(RM) *.o
    
all: clean game
    
test: clean tst_rast 

testSound: clean tst_sound
