tst_rast: tst_rast.o raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Constant.o
	cc68x -g tst_rast.o raster.o Objects.o Model.o Renderer.o Events.o  Constant.o -o tst

game: raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Tron.o Constant.o mSetScrn.o
	cc68x -g raster.o rast_asm.o Objects.o Model.o Renderer.o Events.o Tron.o Constant.o mSetScrn.o -o Tron

tst_sound: TST_PSG.o PSG.o
	cc68x -g TST_PSG.o PSG.o -o psg
	
PSG.o: PSG.c PSG.h
	cc68x -g -c PSG.c

TST_PSG.o: TST_PSG.c PSG.h
	cc68x -g -c TST_PSG.c
	
Tron.o: Tron.c Tron.h    
	cc68x -g -c Tron.c
    
tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

Events.o: Events.c Events.h
	cc68x -g -c Events.c

Constant.o: Constant.c Constant.h
	cc68x -g -c Constant.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

Objects.o: Objects.c Objects.h
	cc68x -g -c Objects.c

Model.o: Model.c Model.h
	cc68x -g -c Model.c

Renderer.o: Renderer.c Renderer.h
	cc68x -g -c Renderer.c

phys:clean phys.o pb_asm.o
	$(RM) phys
	cc68x -g phys.o pb_asm.o -o phys
    
phys.o: physbase.c
	$(RM) phys.o
	cc68x -g -c physbase.c -o phys.o
    
mSetScrn.o: mSetScrn.s
	$(RM) mSetScrn.o
	gen -D -L2 mSetScrn.s

clean:
	$(RM) *.o
    
all: clean game
    
test: clean tst_rast 

testSound: clean tst_sound
